# Generated by Django 5.2.17 on 2026-09-18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalogo", "0001_initial"),
        ("proformas", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("fecha_confirmacion", models.DateTimeField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalogo.valorcatalogo"
                    ),
                ),
                (
                    "proforma",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT, to="proformas.proforma"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"db_table": "pedidos"},
        ),
        migrations.CreateModel(
            name="TransicionEstadoPedido",
            fields=[
                (
                    "estado_destino",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalogo.valorcatalogo",
                    ),
                ),
                (
                    "estado_origen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalogo.valorcatalogo",
                    ),
                ),
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "estado_origen",
                        "estado_destino",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={"db_table": "transiciones_estado_pedido"},
        ),
    ]
