# Generated by Django 5.2.17 on 2026-09-18 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('proformas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_confirmacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proforma', models.OneToOneField(db_column='proforma_id', on_delete=django.db.models.deletion.PROTECT, related_name='pedido', to='proformas.proforma')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.valorcatalogo')),
            ],
            options={
                'db_table': 'pedidos',
            },
        ),
        migrations.CreateModel(
            name='TransicionEstadoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destino', models.ForeignKey(db_column='estado_destino_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.valorcatalogo')),
                ('origen', models.ForeignKey(db_column='estado_origen_id', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.valorcatalogo')),
            ],
            options={
                'db_table': 'transiciones_estado_pedido',
                'constraints': [models.UniqueConstraint(fields=('origen', 'destino'), name='pk_transicion_estado')],
            },
        ),
    ]
