# Generated by Django 5.2.17 on 2026-09-18 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_product_productdiscount_chairproduct_floorproduct_and_more"),
        ("quotations", "0002_furniturespecification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("confirmed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quotation",
                    models.OneToOneField(
                        db_column="proforma_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order",
                        to="quotations.quotation",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.catalogvalue"
                    ),
                ),
            ],
            options={
                "db_table": "pedidos",
            },
        ),
        migrations.CreateModel(
            name="OrderTransition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        db_column="estado_origen_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        db_column="estado_destino_id",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="catalog.catalogvalue",
                    ),
                ),
            ],
            options={
                "db_table": "transiciones_estado_pedido",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "target"), name="pk_transicion_estado"
                    )
                ],
            },
        ),
    ]
