# Generated by Django 5.2.17 on 2026-09-18 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.IntegerField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pedidos.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='movimientos_stock.movimientostock')),
                ('tipo_movimiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.valorcatalogo')),
            ],
            options={
                'db_table': 'movimientos_stock',
                'constraints': [models.CheckConstraint(condition=models.Q(('cantidad', 0), _negated=True), name='ck_movimiento_stock_cantidad_no_cero'), models.UniqueConstraint(condition=models.Q(('referencia__isnull', False)), fields=('referencia',), name='uq_reversa_por_venta')],
            },
        ),
    ]
