# Generated by Django 5.2.17 on 2026-09-18 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField(unique=True)),
                ('nombre_completo', models.CharField(max_length=250)),
                ('monto_en_letras', models.TextField()),
                ('concepto', models.TextField()),
                ('numero_cheque', models.CharField(blank=True, max_length=80, null=True)),
                ('banco', models.CharField(blank=True, max_length=150, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pago_actual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('a_cuenta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(default='EMITIDO', max_length=10)),
                ('fecha', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pedidos.pedido')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.valorcatalogo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recibos',
            },
        ),
    ]
