# Generated by Django 5.2.17 on 2026-09-18 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField(editable=False, unique=True)),
                ('nombre_completo', models.CharField(max_length=250)),
                ('monto_literal', models.TextField()),
                ('concepto', models.TextField()),
                ('numero_cheque', models.CharField(blank=True, max_length=80)),
                ('banco', models.CharField(blank=True, max_length=150)),
                ('total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('pago_actual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('a_cuenta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('EMITIDO', 'Emitido'), ('ANULADO', 'Anulado')], default='EMITIDO', max_length=10)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recibos', to='pedidos.pedido')),
                ('tipo_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.valorcatalogo')),
            ],
            options={
                'db_table': 'recibos',
                'indexes': [models.Index(fields=['pedido'], name='ix_recibos_pedido'), models.Index(fields=['fecha'], name='ix_recibos_fecha'), models.Index(fields=['tipo_pago'], name='ix_recibos_tipo_pago')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total__gt', 0)), name='ck_recibo_total_positive'), models.CheckConstraint(condition=models.Q(('pago_actual__gt', 0)), name='ck_recibo_pago_actual_positive'), models.CheckConstraint(condition=models.Q(('a_cuenta__gte', 0)), name='ck_recibo_a_cuenta_nonnegative'), models.CheckConstraint(condition=models.Q(('saldo__gte', 0)), name='ck_recibo_saldo_nonnegative')],
            },
        ),
    ]
