# Generated by Django 5.2.17 on 2026-09-18 04:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_product_productdiscount_chairproduct_floorproduct_and_more"),
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.BigIntegerField(editable=False, null=True, unique=True)),
                ("title", models.CharField(blank=True, max_length=250)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("delivery_term", models.CharField(blank=True, max_length=100)),
                ("offer_validity", models.SmallIntegerField(blank=True, null=True)),
                (
                    "advance_percentage",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("discount_total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("observations", models.TextField(blank=True)),
                ("prospect_name", models.CharField(blank=True, max_length=250)),
                ("prospect_company", models.CharField(blank=True, max_length=200)),
                ("prospect_phone", models.CharField(blank=True, max_length=40)),
                ("prospect_address", models.TextField(blank=True)),
                ("customer_name_snapshot", models.CharField(blank=True, max_length=300)),
                ("customer_company_snapshot", models.CharField(blank=True, max_length=200)),
                ("customer_phone_snapshot", models.CharField(blank=True, max_length=40)),
                ("customer_address_snapshot", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations_by_currency",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="customers.customer",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations_sold",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations_by_status",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotations_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "proformas",
            },
        ),
        migrations.CreateModel(
            name="QuotationLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("description", models.TextField(blank=True)),
                ("quantity", models.IntegerField()),
                (
                    "calculation_mode",
                    models.CharField(
                        choices=[("PRECIO_UNITARIO", "Unit"), ("TOTAL_NEGOCIADO", "Negotiated")],
                        default="PRECIO_UNITARIO",
                        max_length=20,
                    ),
                ),
                ("unit_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                (
                    "negotiated_amount",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
                ),
                ("discount", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_lines_by_type",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.product",
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="lines",
                        to="quotations.quotation",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="quotation_lines_by_unit",
                        to="catalog.catalogvalue",
                    ),
                ),
            ],
            options={
                "db_table": "proformas_detalle",
            },
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("offer_validity__isnull", True), ("offer_validity__gte", 0), _connector="OR"
                ),
                name="ck_proforma_validez_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("advance_percentage__isnull", True),
                    models.Q(("advance_percentage__gte", 0), ("advance_percentage__lte", 100)),
                    _connector="OR",
                ),
                name="ck_proforma_adelanto",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subtotal__gte", 0), ("discount_total__gte", 0), ("total__gte", 0)
                ),
                name="ck_proforma_importes",
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)), name="ck_detalle_cantidad_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="quotationline",
            constraint=models.CheckConstraint(
                condition=models.Q(("unit_price__gte", 0)), name="ck_detalle_precio_nonnegative"
            ),
        ),
    ]
