# Generated by Django 5.2.17 on 2026-09-18 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0003_product_productdiscount_chairproduct_floorproduct_and_more"),
        ("quotations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FurnitureSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("schema_version", models.SmallIntegerField(default=1)),
                ("thickness", models.JSONField(blank=True, null=True)),
                ("primary_color", models.CharField(blank=True, max_length=150)),
                ("secondary_color", models.CharField(blank=True, max_length=150)),
                ("dimensions", models.JSONField(blank=True, null=True)),
                ("accessories", models.JSONField(blank=True, null=True)),
                ("observations", models.TextField(blank=True)),
                (
                    "furniture_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "line",
                    models.OneToOneField(
                        db_column="proforma_detalle_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="furniture_specification",
                        to="quotations.quotationline",
                    ),
                ),
            ],
            options={
                "db_table": "especificaciones_mueble",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("schema_version", 1)),
                        name="ck_especificacion_schema_version",
                    )
                ],
            },
        ),
    ]
