# Generated by Django 5.2.17 on 2026-09-18 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_product_productdiscount_chairproduct_floorproduct_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("first_names", models.CharField(blank=True, max_length=150)),
                ("last_names", models.CharField(blank=True, max_length=150)),
                ("company", models.CharField(blank=True, max_length=200)),
                ("phone", models.CharField(blank=True, max_length=40)),
                ("address", models.TextField(blank=True)),
                ("observations", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.catalogvalue"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customers_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "clientes",
                "indexes": [
                    models.Index(fields=["customer_type"], name="ix_clientes_tipo"),
                    models.Index(fields=["active"], name="ix_clientes_activo"),
                    models.Index(fields=["company"], name="ix_clientes_empresa"),
                ],
            },
        ),
    ]
