# Generated by Django 5.2.17 on 2026-09-18 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(blank=True, max_length=150)),
                ('apellidos', models.CharField(blank=True, max_length=150)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('celular', models.CharField(blank=True, max_length=40)),
                ('direccion', models.TextField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers_updated', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
                ('tipo_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.valorcatalogo')),
            ],
            options={
                'db_table': 'clientes',
                'indexes': [models.Index(fields=['tipo_cliente'], name='ix_clientes_tipo'), models.Index(fields=['activo'], name='ix_clientes_activo'), models.Index(fields=['empresa'], name='ix_clientes_empresa')],
            },
        ),
    ]
