# Generated by Django 5.2.17 on 2026-09-18 05:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_product_productdiscount_chairproduct_floorproduct_and_more"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Receipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.BigIntegerField(editable=False, unique=True)),
                ("full_name", models.CharField(max_length=250)),
                ("amount_in_words", models.TextField()),
                ("concept", models.TextField()),
                ("check_number", models.CharField(blank=True, max_length=80)),
                ("bank", models.CharField(blank=True, max_length=150)),
                ("total", models.DecimalField(decimal_places=2, max_digits=14)),
                ("current_payment", models.DecimalField(decimal_places=2, max_digits=14)),
                ("on_account", models.DecimalField(decimal_places=2, max_digits=14)),
                ("balance", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[("EMITIDO", "Emitido"), ("ANULADO", "Anulado")],
                        default="EMITIDO",
                        max_length=10,
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="orders.order",
                    ),
                ),
                (
                    "payment_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="catalog.catalogvalue"
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recibos",
                "indexes": [
                    models.Index(fields=["order"], name="ix_recibos_pedido"),
                    models.Index(fields=["date"], name="ix_recibos_fecha"),
                    models.Index(fields=["payment_type"], name="ix_recibos_tipo_pago"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("total__gt", 0)), name="ck_recibo_total_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("current_payment__gt", 0)),
                        name="ck_recibo_pago_actual_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("on_account__gte", 0)),
                        name="ck_recibo_a_cuenta_nonnegative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("balance__gte", 0)), name="ck_recibo_saldo_nonnegative"
                    ),
                ],
            },
        ),
    ]
