# Generated by Django 5.2.17 on 2026-09-18 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'concepto de catálogo',
                'db_table': 'catalogo_conceptos',
            },
        ),
        migrations.CreateModel(
            name='ValorCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='catalogo.conceptocatalogo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'catalogo_valores',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('precio_lista', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_by_categoria', to='catalogo.valorcatalogo')),
                ('unidad_stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products_by_unidad_stock', to='catalogo.valorcatalogo')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='ProductoPiso',
            fields=[
                ('producto', models.OneToOneField(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='piso', serialize=False, to='catalogo.producto')),
                ('modelo', models.CharField(blank=True, max_length=150)),
                ('espesor_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('largo_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('m2_por_caja', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('acabado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pisos_por_acabado', to='catalogo.valorcatalogo')),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('diseno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pisos_por_diseno', to='catalogo.valorcatalogo')),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pisos_por_marca', to='catalogo.valorcatalogo')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pisos_por_material', to='catalogo.valorcatalogo')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pisos_por_tipo', to='catalogo.valorcatalogo')),
            ],
            options={
                'db_table': 'productos_piso',
            },
        ),
        migrations.CreateModel(
            name='ProductoSilla',
            fields=[
                ('producto', models.OneToOneField(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='silla', serialize=False, to='catalogo.producto')),
                ('modelo', models.CharField(blank=True, max_length=150)),
                ('especificaciones', models.JSONField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('color_primario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sillas_color_primario', to='catalogo.valorcatalogo')),
                ('color_secundario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sillas_color_secundario', to='catalogo.valorcatalogo')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sillas_por_marca', to='catalogo.valorcatalogo')),
            ],
            options={
                'db_table': 'productos_silla',
            },
        ),
        migrations.CreateModel(
            name='DescuentoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_antes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('precio_ahora', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='descuento', to='catalogo.producto')),
            ],
            options={
                'db_table': 'productos_descuento',
                'constraints': [models.CheckConstraint(condition=models.Q(('precio_antes__gte', 0), ('precio_ahora__gte', 0)), name='ck_descuento_precios_nonnegative'), models.CheckConstraint(condition=models.Q(('precio_ahora__lt', models.F('precio_antes'))), name='ck_descuento_precio_reducido'), models.CheckConstraint(condition=models.Q(('fecha_fin__isnull', True), ('fecha_inicio__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='ck_descuento_fechas')],
            },
        ),
        migrations.AddIndex(
            model_name='valorcatalogo',
            index=models.Index(fields=['concepto'], name='ix_catalogo_valores_concepto'),
        ),
        migrations.AddIndex(
            model_name='valorcatalogo',
            index=models.Index(fields=['activo'], name='ix_catalogo_valores_activo'),
        ),
        migrations.AddConstraint(
            model_name='valorcatalogo',
            constraint=models.UniqueConstraint(fields=('concepto', 'codigo'), name='uq_catalogo_valor_codigo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['categoria'], name='ix_productos_categoria'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['unidad_stock'], name='ix_productos_unidad_stock'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['activo'], name='ix_productos_activo'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['nombre'], name='ix_productos_nombre'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_lista__gte', 0)), name='ck_productos_precio_lista_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='ck_productos_stock_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productopiso',
            constraint=models.CheckConstraint(condition=models.Q(('espesor_mm__isnull', True), ('espesor_mm__gt', 0), _connector='OR'), name='ck_piso_espesor_positive'),
        ),
        migrations.AddConstraint(
            model_name='productopiso',
            constraint=models.CheckConstraint(condition=models.Q(('largo_mm__isnull', True), ('largo_mm__gt', 0), _connector='OR'), name='ck_piso_largo_positive'),
        ),
        migrations.AddConstraint(
            model_name='productopiso',
            constraint=models.CheckConstraint(condition=models.Q(('ancho_mm__isnull', True), ('ancho_mm__gt', 0), _connector='OR'), name='ck_piso_ancho_positive'),
        ),
        migrations.AddConstraint(
            model_name='productopiso',
            constraint=models.CheckConstraint(condition=models.Q(('m2_por_caja__isnull', True), ('m2_por_caja__gt', 0), _connector='OR'), name='ck_piso_m2_caja_positive'),
        ),
        migrations.AddConstraint(
            model_name='productosilla',
            constraint=models.CheckConstraint(condition=models.Q(('color_secundario__isnull', True), ('color_primario__isnull', False), _connector='OR'), name='ck_silla_color_secundario_requiere_primario'),
        ),
        migrations.AddConstraint(
            model_name='productosilla',
            constraint=models.CheckConstraint(condition=models.Q(('color_primario__isnull', True), ('color_secundario__isnull', True), models.Q(('color_primario', models.F('color_secundario')), _negated=True), _connector='OR'), name='ck_silla_colores_distintos'),
        ),
    ]
