# Generated by Django 5.2.17 on 2026-09-18 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_integridad_catalogo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='descuentoproducto',
            constraint=models.CheckConstraint(condition=models.Q(('precio_antes__gte', models.F('precio_ahora'))), name='ck_descuento_precios_ordenados'),
        ),
        migrations.AddConstraint(
            model_name='descuentoproducto',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_inicio__isnull', True), ('fecha_fin__isnull', True), ('fecha_fin__gte', models.F('fecha_inicio')), _connector='OR'), name='ck_descuento_fechas_ordenadas'),
        ),
    ]
