# Generated by Django 5.2.17 on 2026-09-22 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_descuentoproducto_ck_descuento_precios_ordenados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen_principal_variantes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
