# Generated by Django 5.2.17 on 2026-09-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_media_persistente_f077'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen_principal_dimensiones',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
