# Generated by Django 5.2.17 on 2026-09-18 06:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField(null=True, unique=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('jefe_taller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(db_column='pedido_id', on_delete=django.db.models.deletion.PROTECT, related_name='orden_trabajo', to='pedidos.pedido')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.valorcatalogo')),
            ],
            options={
                'db_table': 'ordenes_trabajo',
            },
        ),
    ]
