# Generated by Django 5.2.17 on 2026-09-18 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("catalog", "0003_product_productdiscount_chairproduct_floorproduct_and_more"),
        ("inventory", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="orders.order",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="catalog.product"
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="reference",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.stockmovement",
            ),
        ),
    ]
