# Generated by Django 5.2.17 on 2026-09-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_stockmovement_ck_movimiento_stock_cantidad_no_cero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmovement",
            name="observations",
            field=models.TextField(blank=True),
        ),
    ]
