# Generated by Django 5.2.17 on 2026-09-18 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField(editable=False, unique=True)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('actualizado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pedido', models.OneToOneField(db_column='pedido_id', on_delete=django.db.models.deletion.PROTECT, to='pedidos.pedido')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nota_entregas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notas_entrega',
                'indexes': [models.Index(fields=['vendedor'], name='ix_notas_entrega_vendedor'), models.Index(fields=['fecha'], name='ix_notas_entrega_fecha')],
            },
        ),
    ]
