# Generated by Django 5.2.17 on 2026-09-18 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cantidad', models.IntegerField()),
                ('modo_calculo', models.CharField(default='PRECIO_UNITARIO', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('importe_negociado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_antes_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_ahora_snapshot', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('tipo_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.valorcatalogo')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.valorcatalogo')),
            ],
            options={
                'db_table': 'proformas_detalle',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionMueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.SmallIntegerField(default=1)),
                ('espesor', models.JSONField(blank=True, null=True)),
                ('color_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('color_secundario', models.CharField(blank=True, max_length=150, null=True)),
                ('dimensiones', models.JSONField(blank=True, null=True)),
                ('accesorios', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('proforma_detalle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proformas.detalleproforma')),
                ('tipo_mueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.valorcatalogo')),
            ],
            options={
                'db_table': 'especificaciones_mueble',
            },
        ),
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField(unique=True)),
                ('titulo', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha', models.DateField()),
                ('plazo_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('validez_oferta', models.SmallIntegerField(blank=True, null=True)),
                ('porcentaje_adelanto', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('prospecto_nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('prospecto_empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('prospecto_celular', models.CharField(blank=True, max_length=40, null=True)),
                ('prospecto_direccion', models.TextField(blank=True, null=True)),
                ('cliente_nombre_snapshot', models.CharField(blank=True, max_length=300, null=True)),
                ('cliente_empresa_snapshot', models.CharField(blank=True, max_length=200, null=True)),
                ('cliente_celular_snapshot', models.CharField(blank=True, max_length=40, null=True)),
                ('cliente_direccion_snapshot', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.valorcatalogo')),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalogo.valorcatalogo')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proformas',
            },
        ),
        migrations.AddField(
            model_name='detalleproforma',
            name='proforma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='proformas.proforma'),
        ),
        migrations.AddConstraint(
            model_name='detalleproforma',
            constraint=models.UniqueConstraint(fields=('proforma', 'id'), name='uq_proforma_detalle_par'),
        ),
    ]
