# Generated by Django 5.2.17 on 2026-09-18 06:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField(editable=False, null=True, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=250)),
                ('fecha', models.DateField(default=django.utils.timezone.localdate)),
                ('plazo_entrega', models.CharField(blank=True, max_length=100)),
                ('vigencia_oferta', models.SmallIntegerField(blank=True, null=True)),
                ('porcentaje_anticipo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuento_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.TextField(blank=True)),
                ('nombre_prospecto', models.CharField(blank=True, max_length=250)),
                ('empresa_prospecto', models.CharField(blank=True, max_length=200)),
                ('celular_prospecto', models.CharField(blank=True, max_length=40)),
                ('direccion_prospecto', models.TextField(blank=True)),
                ('cliente_nombre_snapshot', models.CharField(blank=True, max_length=300)),
                ('cliente_empresa_snapshot', models.CharField(blank=True, max_length=200)),
                ('cliente_celular_snapshot', models.CharField(blank=True, max_length=40)),
                ('cliente_direccion_snapshot', models.TextField(blank=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proformas_actualizadas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proformas_creadas', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas_por_moneda', to='catalogo.valorcatalogo')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas_por_estado', to='catalogo.valorcatalogo')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proformas_vendidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proformas',
            },
        ),
        migrations.CreateModel(
            name='DetalleProforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.IntegerField()),
                ('modo_calculo', models.CharField(choices=[('PRECIO_UNITARIO', 'Unit'), ('TOTAL_NEGOCIADO', 'Negotiated')], default='PRECIO_UNITARIO', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monto_negociado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.producto')),
                ('tipo_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_detalles_by_tipo', to='catalogo.valorcatalogo')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proforma_detalles_by_unidad', to='catalogo.valorcatalogo')),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles', to='proformas.proforma')),
            ],
            options={
                'db_table': 'proformas_detalle',
            },
        ),
        migrations.CreateModel(
            name='EspecificacionMueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_schema', models.SmallIntegerField(default=1)),
                ('espesor', models.JSONField(blank=True, null=True)),
                ('color_primario', models.CharField(blank=True, max_length=150)),
                ('color_secundario', models.CharField(blank=True, max_length=150)),
                ('dimensiones', models.JSONField(blank=True, null=True)),
                ('accesorios', models.JSONField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('detalle', models.OneToOneField(db_column='proforma_detalle_id', on_delete=django.db.models.deletion.CASCADE, related_name='especificacion_mueble', to='proformas.detalleproforma')),
                ('tipo_mueble', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalogo.valorcatalogo')),
            ],
            options={
                'db_table': 'especificaciones_mueble',
                'constraints': [models.CheckConstraint(condition=models.Q(('version_schema', 1)), name='ck_especificacion_version_schema')],
            },
        ),
        migrations.AddConstraint(
            model_name='proforma',
            constraint=models.CheckConstraint(condition=models.Q(('vigencia_oferta__isnull', True), ('vigencia_oferta__gte', 0), _connector='OR'), name='ck_proforma_validez_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='proforma',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje_anticipo__isnull', True), models.Q(('porcentaje_anticipo__gte', 0), ('porcentaje_anticipo__lte', 100)), _connector='OR'), name='ck_proforma_adelanto'),
        ),
        migrations.AddConstraint(
            model_name='proforma',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0), ('descuento_total__gte', 0), ('total__gte', 0)), name='ck_proforma_importes'),
        ),
        migrations.AddConstraint(
            model_name='detalleproforma',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='ck_detalle_cantidad_positive'),
        ),
        migrations.AddConstraint(
            model_name='detalleproforma',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='ck_detalle_precio_nonnegative'),
        ),
    ]
