# Generated by Django 5.2.17 on 2026-09-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_descuentoproducto_ck_descuento_precios_ordenados_and_more'),
        ('proformas', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='detalleproforma',
            constraint=models.CheckConstraint(condition=models.Q(('modo_calculo__in', ['PRECIO_UNITARIO', 'TOTAL_NEGOCIADO'])), name='ck_detalle_modo_calculo'),
        ),
        migrations.AddConstraint(
            model_name='detalleproforma',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('importe_negociado__isnull', True), ('modo_calculo', 'PRECIO_UNITARIO')), models.Q(('importe_negociado__isnull', False), ('modo_calculo', 'TOTAL_NEGOCIADO')), _connector='OR'), name='ck_detalle_importe_negociado'),
        ),
    ]
