# Generated by Django 5.2.17 on 2026-09-18 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0001_initial'),
        ('proformas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Captura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_idempotencia', models.UUIDField(unique=True)),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('capturado_at', models.DateTimeField()),
                ('texto_transcrito', models.TextField(blank=True, null=True)),
                ('texto_normalizado', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proformas.proforma')),
                ('proforma_detalle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proformas.detalleproforma')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'capturas',
            },
        ),
        migrations.CreateModel(
            name='IntentoCaptura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_intento', models.IntegerField()),
                ('estado', models.CharField(default='PENDIENTE', max_length=20)),
                ('etapa_alcanzada', models.CharField(blank=True, max_length=20, null=True)),
                ('input_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('modelo_asr_version', models.CharField(blank=True, max_length=150, null=True)),
                ('modelo_nlp_version', models.CharField(blank=True, max_length=150, null=True)),
                ('inicio_at', models.DateTimeField()),
                ('fin_at', models.DateTimeField(blank=True, null=True)),
                ('latencia_total_ms', models.IntegerField(blank=True, null=True)),
                ('latencia_asr_ms', models.IntegerField(blank=True, null=True)),
                ('latencia_nlp_ms', models.IntegerField(blank=True, null=True)),
                ('error_codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('labels_detectados', models.JSONField(blank=True, null=True)),
                ('resultado_raw', models.JSONField(blank=True, null=True)),
                ('captura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='capturas.captura')),
            ],
            options={
                'db_table': 'intentos_captura',
            },
        ),
        migrations.CreateModel(
            name='ItemHumano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('espesor', models.JSONField(blank=True, null=True)),
                ('color_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('color_secundario', models.CharField(blank=True, max_length=150, null=True)),
                ('dimensiones', models.JSONField(blank=True, null=True)),
                ('accesorios', models.JSONField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('revisado_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'items_humano',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionNLP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_metrica', models.CharField(default='V1', max_length=50)),
                ('inicio_revision_at', models.DateTimeField(blank=True, null=True)),
                ('fin_revision_at', models.DateTimeField(blank=True, null=True)),
                ('tiempo_revision_ms', models.IntegerField(blank=True, null=True)),
                ('campos_totales', models.IntegerField(default=0)),
                ('campos_corregidos', models.IntegerField(default=0)),
                ('campos_agregados', models.IntegerField(default=0)),
                ('campos_eliminados', models.IntegerField(default=0)),
                ('precision_item', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('precision_campo', models.DecimalField(blank=True, decimal_places=5, max_digits=6, null=True)),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('item_humano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='capturas.itemhumano')),
            ],
            options={
                'db_table': 'evaluaciones_nlp',
            },
        ),
        migrations.CreateModel(
            name='ItemIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('espesor', models.JSONField(blank=True, null=True)),
                ('color_principal', models.CharField(blank=True, max_length=150, null=True)),
                ('color_secundario', models.CharField(blank=True, max_length=150, null=True)),
                ('dimensiones', models.JSONField(blank=True, null=True)),
                ('accesorios', models.JSONField(blank=True, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('intento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='capturas.intentocaptura')),
            ],
            options={
                'db_table': 'items_ia',
            },
        ),
        migrations.AddField(
            model_name='itemhumano',
            name='item_ia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='capturas.itemia'),
        ),
        migrations.CreateModel(
            name='MedicionProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo_version', models.CharField(blank=True, max_length=80, null=True)),
                ('inicio_at', models.DateTimeField()),
                ('fin_at', models.DateTimeField()),
                ('tiempo_total_ms', models.IntegerField()),
                ('num_items', models.IntegerField(default=1)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('metodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.valorcatalogo')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proformas.proforma')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mediciones_proceso',
            },
        ),
        migrations.CreateModel(
            name='TrabajoOutbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='PROCESAR_CAPTURA', max_length=60)),
                ('clave_unica', models.CharField(max_length=180, unique=True)),
                ('disponible_at', models.DateTimeField()),
                ('publicado_at', models.DateTimeField(blank=True, null=True)),
                ('intentos_publicacion', models.IntegerField(default=0)),
                ('ultimo_error', models.TextField(blank=True, null=True)),
                ('intento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='capturas.intentocaptura')),
            ],
            options={
                'db_table': 'trabajos_outbox',
            },
        ),
        migrations.AddConstraint(
            model_name='intentocaptura',
            constraint=models.UniqueConstraint(fields=('captura', 'numero_intento'), name='uq_intento_captura_numero'),
        ),
    ]
