# Generated by Django 5.2.17 on 2026-09-22 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_ajuste_indices_operativos_f076'),
        ('proformas', '0004_cierre_reglas_f072'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivoadjunto',
            name='proforma_detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='proformas.detalleproforma'),
        ),
    ]
