-- Ejecutar como propietario de la base, nunca como el rol runtime.
CREATE ROLE homex_runtime LOGIN PASSWORD 'CAMBIAR_FUERA_DE_GIT';
GRANT CONNECT ON DATABASE homex TO homex_runtime;
GRANT USAGE ON SCHEMA public TO homex_runtime;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA public TO homex_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO homex_runtime;
REVOKE CREATE ON SCHEMA public FROM homex_runtime;
REVOKE TRUNCATE, DELETE ON ALL TABLES IN SCHEMA public FROM homex_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE ON TABLES TO homex_runtime;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO homex_runtime;
