# Generated by Django 5.2.17 on 2026-09-18 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_commercial_sequences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("list_price", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("stock", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("observations", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products_by_category",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stock_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="products_by_stock_unit",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "productos",
            },
        ),
        migrations.CreateModel(
            name="ProductDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("price_before", models.DecimalField(decimal_places=2, max_digits=12)),
                ("price_now", models.DecimalField(decimal_places=2, max_digits=12)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="discount",
                        to="catalog.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "productos_descuento",
            },
        ),
        migrations.CreateModel(
            name="ChairProduct",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        db_column="producto_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="chair",
                        serialize=False,
                        to="catalog.product",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=150)),
                ("specifications", models.JSONField(blank=True, null=True)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chair_brands",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chairs_primary_color",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "secondary_color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="chairs_secondary_color",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "productos_silla",
            },
        ),
        migrations.CreateModel(
            name="FloorProduct",
            fields=[
                (
                    "product",
                    models.OneToOneField(
                        db_column="producto_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="floor",
                        serialize=False,
                        to="catalog.product",
                    ),
                ),
                ("model", models.CharField(blank=True, max_length=150)),
                (
                    "thickness_mm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                (
                    "length_mm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "width_mm",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                (
                    "m2_per_box",
                    models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="floor_brands",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "design",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="floor_designs",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "finish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="floor_finishes",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "material",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="floor_materials",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="floor_types",
                        to="catalog.catalogvalue",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "productos_piso",
            },
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["category"], name="ix_productos_categoria"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["stock_unit"], name="ix_productos_unidad_stock"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["active"], name="ix_productos_activo"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["name"], name="ix_productos_nombre"),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("list_price__gte", 0)),
                name="ck_productos_precio_lista_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock__gte", 0)), name="ck_productos_stock_nonnegative"
            ),
        ),
        migrations.AddConstraint(
            model_name="productdiscount",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_before__gte", 0), ("price_now__gte", 0)),
                name="ck_descuento_precios_nonnegative",
            ),
        ),
        migrations.AddConstraint(
            model_name="productdiscount",
            constraint=models.CheckConstraint(
                condition=models.Q(("price_now__lt", models.F("price_before"))),
                name="ck_descuento_precio_reducido",
            ),
        ),
        migrations.AddConstraint(
            model_name="productdiscount",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("start_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="ck_descuento_fechas",
            ),
        ),
        migrations.AddConstraint(
            model_name="chairproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("secondary_color__isnull", True),
                    ("primary_color__isnull", False),
                    _connector="OR",
                ),
                name="ck_silla_color_secundario_requiere_primario",
            ),
        ),
        migrations.AddConstraint(
            model_name="chairproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("primary_color__isnull", True),
                    ("secondary_color__isnull", True),
                    models.Q(("primary_color", models.F("secondary_color")), _negated=True),
                    _connector="OR",
                ),
                name="ck_silla_colores_distintos",
            ),
        ),
        migrations.AddConstraint(
            model_name="floorproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("thickness_mm__isnull", True), ("thickness_mm__gt", 0), _connector="OR"
                ),
                name="ck_piso_espesor_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="floorproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("length_mm__isnull", True), ("length_mm__gt", 0), _connector="OR"
                ),
                name="ck_piso_largo_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="floorproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("width_mm__isnull", True), ("width_mm__gt", 0), _connector="OR"
                ),
                name="ck_piso_ancho_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="floorproduct",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("m2_per_box__isnull", True), ("m2_per_box__gt", 0), _connector="OR"
                ),
                name="ck_piso_m2_caja_positive",
            ),
        ),
    ]
