openapi: 3.0.3
info:
  title: HOMEX Backend API
  version: v1
  description: API comercial de HOMEX.
paths:
  /api/v1/auth/token/:
    post:
      operationId: v1_auth_token_create
      description: |-
        Takes a set of user credentials and returns an access and refresh JSON web
        token pair to prove the authentication of those credentials.
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenObtainPair'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenObtainPair'
          description: ''
  /api/v1/auth/token/refresh/:
    post:
      operationId: v1_auth_token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
  /api/v1/delivery-notes/:
    get:
      operationId: v1_delivery_notes_list
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DeliveryNote'
          description: ''
    post:
      operationId: v1_delivery_notes_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeliveryNote'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/DeliveryNote'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/DeliveryNote'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryNote'
          description: ''
  /api/v1/delivery-notes/{id}/:
    get:
      operationId: v1_delivery_notes_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Un valor de entero único que identifique este delivery note.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryNote'
          description: ''
  /api/v1/quotations/:
    get:
      operationId: v1_quotations_list
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Quotation'
          description: ''
    post:
      operationId: v1_quotations_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quotation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Quotation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Quotation'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quotation'
          description: ''
  /api/v1/quotations/{id}/:
    get:
      operationId: v1_quotations_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Un valor de entero único que identifique este quotation.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quotation'
          description: ''
    put:
      operationId: v1_quotations_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Un valor de entero único que identifique este quotation.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quotation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Quotation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Quotation'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quotation'
          description: ''
    patch:
      operationId: v1_quotations_partial_update
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Un valor de entero único que identifique este quotation.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedQuotation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedQuotation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedQuotation'
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quotation'
          description: ''
    delete:
      operationId: v1_quotations_destroy
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Un valor de entero único que identifique este quotation.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '204':
          description: No response body
  /api/v1/quotations/{id}/submit/:
    post:
      operationId: v1_quotations_submit_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Un valor de entero único que identifique este quotation.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Quotation'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Quotation'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Quotation'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Quotation'
          description: ''
  /api/v1/receipts/:
    get:
      operationId: v1_receipts_list
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Receipt'
          description: ''
    post:
      operationId: v1_receipts_create
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Receipt'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Receipt'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Receipt'
        required: true
      security:
      - jwtAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Receipt'
          description: ''
  /api/v1/receipts/{id}/:
    get:
      operationId: v1_receipts_retrieve
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Un valor de entero único que identifique este receipt.
        required: true
      tags:
      - v1
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Receipt'
          description: ''
  /api/v1/receipts/{id}/void/:
    post:
      operationId: v1_receipts_void_create
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: Un valor de entero único que identifique este receipt.
        required: true
      tags:
      - v1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Receipt'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Receipt'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Receipt'
        required: true
      security:
      - jwtAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Receipt'
          description: ''
components:
  schemas:
    DeliveryNote:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        order:
          type: integer
        seller:
          type: integer
          readOnly: true
        number:
          type: integer
          readOnly: true
        date:
          type: string
          format: date
          readOnly: true
      required:
      - date
      - id
      - number
      - order
      - seller
    PatchedQuotation:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        number:
          type: integer
          readOnly: true
          nullable: true
        customer:
          type: integer
          nullable: true
        seller:
          type: integer
          readOnly: true
        status:
          type: integer
        currency:
          type: integer
        title:
          type: string
          maxLength: 250
        date:
          type: string
          format: date
        subtotal:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
          readOnly: true
        discount_total:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
          readOnly: true
        total:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
          readOnly: true
    Quotation:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        number:
          type: integer
          readOnly: true
          nullable: true
        customer:
          type: integer
          nullable: true
        seller:
          type: integer
          readOnly: true
        status:
          type: integer
        currency:
          type: integer
        title:
          type: string
          maxLength: 250
        date:
          type: string
          format: date
        subtotal:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
          readOnly: true
        discount_total:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
          readOnly: true
        total:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
          readOnly: true
      required:
      - currency
      - discount_total
      - id
      - number
      - seller
      - status
      - subtotal
      - total
    Receipt:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        number:
          type: integer
          readOnly: true
        order:
          type: integer
        full_name:
          type: string
          maxLength: 250
        amount_in_words:
          type: string
        concept:
          type: string
        payment_type:
          type: integer
        check_number:
          type: string
          maxLength: 80
        bank:
          type: string
          maxLength: 150
        total:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
          readOnly: true
        current_payment:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
        on_account:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
          readOnly: true
        balance:
          type: string
          format: decimal
          pattern: ^-?\d{0,12}(?:\.\d{0,2})?$
          readOnly: true
        status:
          allOf:
          - $ref: '#/components/schemas/StatusEnum'
          readOnly: true
        date:
          type: string
          format: date
          readOnly: true
      required:
      - amount_in_words
      - balance
      - concept
      - current_payment
      - date
      - full_name
      - id
      - number
      - on_account
      - order
      - payment_type
      - status
      - total
    StatusEnum:
      enum:
      - EMITIDO
      - ANULADO
      type: string
      description: |-
        * `EMITIDO` - Emitido
        * `ANULADO` - Anulado
    TokenObtainPair:
      type: object
      properties:
        username:
          type: string
          writeOnly: true
        password:
          type: string
          writeOnly: true
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          readOnly: true
      required:
      - access
      - password
      - refresh
      - username
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
